insert into Categories (category_id, category_name) values (1, 'n/a');
insert into Categories (category_id, category_name) values (2, 'Health Care');
insert into Categories (category_id, category_name) values (3, 'Finance');
insert into Categories (category_id, category_name) values (4, 'n/a');
insert into Categories (category_id, category_name) values (5, 'Finance');
insert into Categories (category_id, category_name) values (6, 'Health Care');
insert into Categories (category_id, category_name) values (7, 'n/a');
insert into Categories (category_id, category_name) values (8, 'Finance');
insert into Categories (category_id, category_name) values (9, 'Basic Industries');
insert into Categories (category_id, category_name) values (10, 'Consumer Services');
insert into Categories (category_id, category_name) values (11, 'Technology');
insert into Categories (category_id, category_name) values (12, 'Energy');
insert into Categories (category_id, category_name) values (13, 'n/a');
insert into Categories (category_id, category_name) values (14, 'Finance');
insert into Categories (category_id, category_name) values (15, 'Transportation');
insert into Categories (category_id, category_name) values (16, 'Health Care');
insert into Categories (category_id, category_name) values (17, 'Consumer Services');
insert into Categories (category_id, category_name) values (18, 'n/a');
insert into Categories (category_id, category_name) values (19, 'n/a');
insert into Categories (category_id, category_name) values (20, 'Finance');
insert into Categories (category_id, category_name) values (21, 'Capital Goods');
insert into Categories (category_id, category_name) values (22, 'Health Care');
insert into Categories (category_id, category_name) values (23, 'Capital Goods');
insert into Categories (category_id, category_name) values (24, 'Consumer Services');
insert into Categories (category_id, category_name) values (25, 'Health Care');
insert into Categories (category_id, category_name) values (26, 'Finance');
insert into Categories (category_id, category_name) values (27, 'Transportation');
insert into Categories (category_id, category_name) values (28, 'n/a');
insert into Categories (category_id, category_name) values (29, 'Basic Industries');
insert into Categories (category_id, category_name) values (30, 'Technology');
insert into Categories (category_id, category_name) values (31, 'Transportation');
insert into Categories (category_id, category_name) values (32, 'Capital Goods');
insert into Categories (category_id, category_name) values (33, 'Technology');
insert into Categories (category_id, category_name) values (34, 'n/a');
insert into Categories (category_id, category_name) values (35, 'Capital Goods');
insert into Categories (category_id, category_name) values (36, 'n/a');
insert into Categories (category_id, category_name) values (37, 'Energy');
insert into Categories (category_id, category_name) values (38, 'n/a');
insert into Categories (category_id, category_name) values (39, 'Technology');
insert into Categories (category_id, category_name) values (40, 'Transportation');
insert into Categories (category_id, category_name) values (41, 'Consumer Services');
insert into Categories (category_id, category_name) values (42, 'Consumer Durables');
insert into Categories (category_id, category_name) values (43, 'Finance');
insert into Categories (category_id, category_name) values (44, 'Consumer Services');
insert into Categories (category_id, category_name) values (45, 'Technology');
insert into Categories (category_id, category_name) values (46, 'Finance');
insert into Categories (category_id, category_name) values (47, 'Miscellaneous');
insert into Categories (category_id, category_name) values (48, 'n/a');
insert into Categories (category_id, category_name) values (49, 'Finance');
insert into Categories (category_id, category_name) values (50, 'Technology');
insert into Categories (category_id, category_name) values (51, 'Finance');
insert into Categories (category_id, category_name) values (52, 'Finance');
insert into Categories (category_id, category_name) values (53, 'Energy');
insert into Categories (category_id, category_name) values (54, 'n/a');
insert into Categories (category_id, category_name) values (55, 'Finance');
insert into Categories (category_id, category_name) values (56, 'Health Care');
insert into Categories (category_id, category_name) values (57, 'n/a');
insert into Categories (category_id, category_name) values (58, 'n/a');
insert into Categories (category_id, category_name) values (59, 'Finance');
insert into Categories (category_id, category_name) values (60, 'Health Care');
insert into Categories (category_id, category_name) values (61, 'n/a');
insert into Categories (category_id, category_name) values (62, 'Consumer Services');
insert into Categories (category_id, category_name) values (63, 'Energy');
insert into Categories (category_id, category_name) values (64, 'Finance');
insert into Categories (category_id, category_name) values (65, 'Consumer Services');
insert into Categories (category_id, category_name) values (66, 'n/a');
insert into Categories (category_id, category_name) values (67, 'Consumer Services');
insert into Categories (category_id, category_name) values (68, 'n/a');
insert into Categories (category_id, category_name) values (69, 'Transportation');
insert into Categories (category_id, category_name) values (70, 'Health Care');
insert into Categories (category_id, category_name) values (71, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (72, 'Consumer Services');
insert into Categories (category_id, category_name) values (73, 'Transportation');
insert into Categories (category_id, category_name) values (74, 'n/a');
insert into Categories (category_id, category_name) values (75, 'Technology');
insert into Categories (category_id, category_name) values (76, 'Consumer Services');
insert into Categories (category_id, category_name) values (77, 'Consumer Services');
insert into Categories (category_id, category_name) values (78, 'Energy');
insert into Categories (category_id, category_name) values (79, 'Basic Industries');
insert into Categories (category_id, category_name) values (80, 'Public Utilities');
insert into Categories (category_id, category_name) values (81, 'Finance');
insert into Categories (category_id, category_name) values (82, 'Consumer Services');
insert into Categories (category_id, category_name) values (83, 'Technology');
insert into Categories (category_id, category_name) values (84, 'Basic Industries');
insert into Categories (category_id, category_name) values (85, 'Public Utilities');
insert into Categories (category_id, category_name) values (86, 'n/a');
insert into Categories (category_id, category_name) values (87, 'Consumer Services');
insert into Categories (category_id, category_name) values (88, 'n/a');
insert into Categories (category_id, category_name) values (89, 'Technology');
insert into Categories (category_id, category_name) values (90, 'Health Care');
insert into Categories (category_id, category_name) values (91, 'Health Care');
insert into Categories (category_id, category_name) values (92, 'Health Care');
insert into Categories (category_id, category_name) values (93, 'Consumer Services');
insert into Categories (category_id, category_name) values (94, 'Health Care');
insert into Categories (category_id, category_name) values (95, 'n/a');
insert into Categories (category_id, category_name) values (96, 'Technology');
insert into Categories (category_id, category_name) values (97, 'n/a');
insert into Categories (category_id, category_name) values (98, 'n/a');
insert into Categories (category_id, category_name) values (99, 'Basic Industries');
insert into Categories (category_id, category_name) values (100, 'n/a');
insert into Categories (category_id, category_name) values (101, 'Finance');
insert into Categories (category_id, category_name) values (102, 'Energy');
insert into Categories (category_id, category_name) values (103, 'Miscellaneous');
insert into Categories (category_id, category_name) values (104, 'Technology');
insert into Categories (category_id, category_name) values (105, 'Consumer Durables');
insert into Categories (category_id, category_name) values (106, 'Health Care');
insert into Categories (category_id, category_name) values (107, 'Health Care');
insert into Categories (category_id, category_name) values (108, 'Consumer Services');
insert into Categories (category_id, category_name) values (109, 'n/a');
insert into Categories (category_id, category_name) values (110, 'n/a');
insert into Categories (category_id, category_name) values (111, 'n/a');
insert into Categories (category_id, category_name) values (112, 'Technology');
insert into Categories (category_id, category_name) values (113, 'n/a');
insert into Categories (category_id, category_name) values (114, 'Miscellaneous');
insert into Categories (category_id, category_name) values (115, 'Technology');
insert into Categories (category_id, category_name) values (116, 'Miscellaneous');
insert into Categories (category_id, category_name) values (117, 'n/a');
insert into Categories (category_id, category_name) values (118, 'Technology');
insert into Categories (category_id, category_name) values (119, 'Finance');
insert into Categories (category_id, category_name) values (120, 'n/a');
insert into Categories (category_id, category_name) values (121, 'Energy');
insert into Categories (category_id, category_name) values (122, 'Public Utilities');
insert into Categories (category_id, category_name) values (123, 'Consumer Services');
insert into Categories (category_id, category_name) values (124, 'n/a');
insert into Categories (category_id, category_name) values (125, 'Capital Goods');
insert into Categories (category_id, category_name) values (126, 'n/a');
insert into Categories (category_id, category_name) values (127, 'Technology');
insert into Categories (category_id, category_name) values (128, 'n/a');
insert into Categories (category_id, category_name) values (129, 'Health Care');
insert into Categories (category_id, category_name) values (130, 'Health Care');
insert into Categories (category_id, category_name) values (131, 'Technology');
insert into Categories (category_id, category_name) values (132, 'Basic Industries');
insert into Categories (category_id, category_name) values (133, 'Energy');
insert into Categories (category_id, category_name) values (134, 'Technology');
insert into Categories (category_id, category_name) values (135, 'Health Care');
insert into Categories (category_id, category_name) values (136, 'Finance');
insert into Categories (category_id, category_name) values (137, 'Health Care');
insert into Categories (category_id, category_name) values (138, 'n/a');
insert into Categories (category_id, category_name) values (139, 'Health Care');
insert into Categories (category_id, category_name) values (140, 'Technology');
insert into Categories (category_id, category_name) values (141, 'Energy');
insert into Categories (category_id, category_name) values (142, 'Consumer Services');
insert into Categories (category_id, category_name) values (143, 'Finance');
insert into Categories (category_id, category_name) values (144, 'n/a');
insert into Categories (category_id, category_name) values (145, 'Health Care');
insert into Categories (category_id, category_name) values (146, 'Finance');
insert into Categories (category_id, category_name) values (147, 'Health Care');
insert into Categories (category_id, category_name) values (148, 'n/a');
insert into Categories (category_id, category_name) values (149, 'Public Utilities');
insert into Categories (category_id, category_name) values (150, 'Health Care');
insert into Categories (category_id, category_name) values (151, 'n/a');
insert into Categories (category_id, category_name) values (152, 'Transportation');
insert into Categories (category_id, category_name) values (153, 'Energy');
insert into Categories (category_id, category_name) values (154, 'Consumer Services');
insert into Categories (category_id, category_name) values (155, 'Health Care');
insert into Categories (category_id, category_name) values (156, 'Technology');
insert into Categories (category_id, category_name) values (157, 'Health Care');
insert into Categories (category_id, category_name) values (158, 'Finance');
insert into Categories (category_id, category_name) values (159, 'Public Utilities');
insert into Categories (category_id, category_name) values (160, 'Capital Goods');
insert into Categories (category_id, category_name) values (161, 'Energy');
insert into Categories (category_id, category_name) values (162, 'n/a');
insert into Categories (category_id, category_name) values (163, 'Energy');
insert into Categories (category_id, category_name) values (164, 'Consumer Services');
insert into Categories (category_id, category_name) values (165, 'Transportation');
insert into Categories (category_id, category_name) values (166, 'Energy');
insert into Categories (category_id, category_name) values (167, 'Consumer Services');
insert into Categories (category_id, category_name) values (168, 'Finance');
insert into Categories (category_id, category_name) values (169, 'Capital Goods');
insert into Categories (category_id, category_name) values (170, 'Consumer Services');
insert into Categories (category_id, category_name) values (171, 'Consumer Services');
insert into Categories (category_id, category_name) values (172, 'Technology');
insert into Categories (category_id, category_name) values (173, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (174, 'Energy');
insert into Categories (category_id, category_name) values (175, 'n/a');
insert into Categories (category_id, category_name) values (176, 'Basic Industries');
insert into Categories (category_id, category_name) values (177, 'n/a');
insert into Categories (category_id, category_name) values (178, 'n/a');
insert into Categories (category_id, category_name) values (179, 'Technology');
insert into Categories (category_id, category_name) values (180, 'Basic Industries');
insert into Categories (category_id, category_name) values (181, 'Basic Industries');
insert into Categories (category_id, category_name) values (182, 'Energy');
insert into Categories (category_id, category_name) values (183, 'Miscellaneous');
insert into Categories (category_id, category_name) values (184, 'Technology');
insert into Categories (category_id, category_name) values (185, 'Health Care');
insert into Categories (category_id, category_name) values (186, 'Basic Industries');
insert into Categories (category_id, category_name) values (187, 'n/a');
insert into Categories (category_id, category_name) values (188, 'Health Care');
insert into Categories (category_id, category_name) values (189, 'Finance');
insert into Categories (category_id, category_name) values (190, 'Capital Goods');
insert into Categories (category_id, category_name) values (191, 'n/a');
insert into Categories (category_id, category_name) values (192, 'n/a');
insert into Categories (category_id, category_name) values (193, 'Finance');
insert into Categories (category_id, category_name) values (194, 'Technology');
insert into Categories (category_id, category_name) values (195, 'Public Utilities');
insert into Categories (category_id, category_name) values (196, 'Technology');
insert into Categories (category_id, category_name) values (197, 'Basic Industries');
insert into Categories (category_id, category_name) values (198, 'Consumer Services');
insert into Categories (category_id, category_name) values (199, 'Finance');
insert into Categories (category_id, category_name) values (200, 'n/a');
insert into Categories (category_id, category_name) values (201, 'Health Care');
insert into Categories (category_id, category_name) values (202, 'Consumer Durables');
insert into Categories (category_id, category_name) values (203, 'Consumer Services');
insert into Categories (category_id, category_name) values (204, 'Technology');
insert into Categories (category_id, category_name) values (205, 'n/a');
insert into Categories (category_id, category_name) values (206, 'Miscellaneous');
insert into Categories (category_id, category_name) values (207, 'Consumer Services');
insert into Categories (category_id, category_name) values (208, 'Energy');
insert into Categories (category_id, category_name) values (209, 'Health Care');
insert into Categories (category_id, category_name) values (210, 'Finance');
insert into Categories (category_id, category_name) values (211, 'Health Care');
insert into Categories (category_id, category_name) values (212, 'Health Care');
insert into Categories (category_id, category_name) values (213, 'Consumer Services');
insert into Categories (category_id, category_name) values (214, 'Finance');
insert into Categories (category_id, category_name) values (215, 'Capital Goods');
insert into Categories (category_id, category_name) values (216, 'Health Care');
insert into Categories (category_id, category_name) values (217, 'n/a');
insert into Categories (category_id, category_name) values (218, 'Health Care');
insert into Categories (category_id, category_name) values (219, 'Consumer Services');
insert into Categories (category_id, category_name) values (220, 'n/a');
insert into Categories (category_id, category_name) values (221, 'Health Care');
insert into Categories (category_id, category_name) values (222, 'Public Utilities');
insert into Categories (category_id, category_name) values (223, 'Miscellaneous');
insert into Categories (category_id, category_name) values (224, 'Energy');
insert into Categories (category_id, category_name) values (225, 'n/a');
insert into Categories (category_id, category_name) values (226, 'Finance');
insert into Categories (category_id, category_name) values (227, 'Consumer Services');
insert into Categories (category_id, category_name) values (228, 'Finance');
insert into Categories (category_id, category_name) values (229, 'Health Care');
insert into Categories (category_id, category_name) values (230, 'n/a');
insert into Categories (category_id, category_name) values (231, 'n/a');
insert into Categories (category_id, category_name) values (232, 'Energy');
insert into Categories (category_id, category_name) values (233, 'Transportation');
insert into Categories (category_id, category_name) values (234, 'Finance');
insert into Categories (category_id, category_name) values (235, 'Consumer Durables');
insert into Categories (category_id, category_name) values (236, 'Basic Industries');
insert into Categories (category_id, category_name) values (237, 'Health Care');
insert into Categories (category_id, category_name) values (238, 'Consumer Services');
insert into Categories (category_id, category_name) values (239, 'Energy');
insert into Categories (category_id, category_name) values (240, 'Technology');
insert into Categories (category_id, category_name) values (241, 'Public Utilities');
insert into Categories (category_id, category_name) values (242, 'Finance');
insert into Categories (category_id, category_name) values (243, 'Finance');
insert into Categories (category_id, category_name) values (244, 'Transportation');
insert into Categories (category_id, category_name) values (245, 'Capital Goods');
insert into Categories (category_id, category_name) values (246, 'Health Care');
insert into Categories (category_id, category_name) values (247, 'Health Care');
insert into Categories (category_id, category_name) values (248, 'Finance');
insert into Categories (category_id, category_name) values (249, 'Finance');
insert into Categories (category_id, category_name) values (250, 'Consumer Durables');
insert into Categories (category_id, category_name) values (251, 'Consumer Services');
insert into Categories (category_id, category_name) values (252, 'Finance');
insert into Categories (category_id, category_name) values (253, 'Consumer Durables');
insert into Categories (category_id, category_name) values (254, 'Technology');
insert into Categories (category_id, category_name) values (255, 'n/a');
insert into Categories (category_id, category_name) values (256, 'Energy');
insert into Categories (category_id, category_name) values (257, 'n/a');
insert into Categories (category_id, category_name) values (258, 'Basic Industries');
insert into Categories (category_id, category_name) values (259, 'Energy');
insert into Categories (category_id, category_name) values (260, 'n/a');
insert into Categories (category_id, category_name) values (261, 'Finance');
insert into Categories (category_id, category_name) values (262, 'n/a');
insert into Categories (category_id, category_name) values (263, 'Basic Industries');
insert into Categories (category_id, category_name) values (264, 'Consumer Services');
insert into Categories (category_id, category_name) values (265, 'Energy');
insert into Categories (category_id, category_name) values (266, 'n/a');
insert into Categories (category_id, category_name) values (267, 'Consumer Services');
insert into Categories (category_id, category_name) values (268, 'Consumer Services');
insert into Categories (category_id, category_name) values (269, 'Finance');
insert into Categories (category_id, category_name) values (270, 'n/a');
insert into Categories (category_id, category_name) values (271, 'Consumer Services');
insert into Categories (category_id, category_name) values (272, 'n/a');
insert into Categories (category_id, category_name) values (273, 'Health Care');
insert into Categories (category_id, category_name) values (274, 'Basic Industries');
insert into Categories (category_id, category_name) values (275, 'Basic Industries');
insert into Categories (category_id, category_name) values (276, 'n/a');
insert into Categories (category_id, category_name) values (277, 'Transportation');
insert into Categories (category_id, category_name) values (278, 'Health Care');
insert into Categories (category_id, category_name) values (279, 'Health Care');
insert into Categories (category_id, category_name) values (280, 'Capital Goods');
insert into Categories (category_id, category_name) values (281, 'n/a');
insert into Categories (category_id, category_name) values (282, 'Finance');
insert into Categories (category_id, category_name) values (283, 'Health Care');
insert into Categories (category_id, category_name) values (284, 'Health Care');
insert into Categories (category_id, category_name) values (285, 'n/a');
insert into Categories (category_id, category_name) values (286, 'Public Utilities');
insert into Categories (category_id, category_name) values (287, 'Consumer Services');
insert into Categories (category_id, category_name) values (288, 'n/a');
insert into Categories (category_id, category_name) values (289, 'Public Utilities');
insert into Categories (category_id, category_name) values (290, 'Consumer Services');
insert into Categories (category_id, category_name) values (291, 'Health Care');
insert into Categories (category_id, category_name) values (292, 'Finance');
insert into Categories (category_id, category_name) values (293, 'Finance');
insert into Categories (category_id, category_name) values (294, 'Finance');
insert into Categories (category_id, category_name) values (295, 'Public Utilities');
insert into Categories (category_id, category_name) values (296, 'Consumer Services');
insert into Categories (category_id, category_name) values (297, 'Technology');
insert into Categories (category_id, category_name) values (298, 'n/a');
insert into Categories (category_id, category_name) values (299, 'Basic Industries');
insert into Categories (category_id, category_name) values (300, 'n/a');
insert into Categories (category_id, category_name) values (301, 'Capital Goods');
insert into Categories (category_id, category_name) values (302, 'Health Care');
insert into Categories (category_id, category_name) values (303, 'Health Care');
insert into Categories (category_id, category_name) values (304, 'n/a');
insert into Categories (category_id, category_name) values (305, 'Basic Industries');
insert into Categories (category_id, category_name) values (306, 'Energy');
insert into Categories (category_id, category_name) values (307, 'Finance');
insert into Categories (category_id, category_name) values (308, 'n/a');
insert into Categories (category_id, category_name) values (309, 'Consumer Services');
insert into Categories (category_id, category_name) values (310, 'Finance');
insert into Categories (category_id, category_name) values (311, 'n/a');
insert into Categories (category_id, category_name) values (312, 'n/a');
insert into Categories (category_id, category_name) values (313, 'Health Care');
insert into Categories (category_id, category_name) values (314, 'Consumer Services');
insert into Categories (category_id, category_name) values (315, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (316, 'n/a');
insert into Categories (category_id, category_name) values (317, 'Finance');
insert into Categories (category_id, category_name) values (318, 'Finance');
insert into Categories (category_id, category_name) values (319, 'Consumer Services');
insert into Categories (category_id, category_name) values (320, 'Public Utilities');
insert into Categories (category_id, category_name) values (321, 'Technology');
insert into Categories (category_id, category_name) values (322, 'n/a');
insert into Categories (category_id, category_name) values (323, 'Energy');
insert into Categories (category_id, category_name) values (324, 'Basic Industries');
insert into Categories (category_id, category_name) values (325, 'Health Care');
insert into Categories (category_id, category_name) values (326, 'Technology');
insert into Categories (category_id, category_name) values (327, 'Health Care');
insert into Categories (category_id, category_name) values (328, 'Capital Goods');
insert into Categories (category_id, category_name) values (329, 'n/a');
insert into Categories (category_id, category_name) values (330, 'n/a');
insert into Categories (category_id, category_name) values (331, 'Finance');
insert into Categories (category_id, category_name) values (332, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (333, 'n/a');
insert into Categories (category_id, category_name) values (334, 'Consumer Durables');
insert into Categories (category_id, category_name) values (335, 'Finance');
insert into Categories (category_id, category_name) values (336, 'Energy');
insert into Categories (category_id, category_name) values (337, 'Basic Industries');
insert into Categories (category_id, category_name) values (338, 'Health Care');
insert into Categories (category_id, category_name) values (339, 'n/a');
insert into Categories (category_id, category_name) values (340, 'Energy');
insert into Categories (category_id, category_name) values (341, 'Technology');
insert into Categories (category_id, category_name) values (342, 'Finance');
insert into Categories (category_id, category_name) values (343, 'Technology');
insert into Categories (category_id, category_name) values (344, 'n/a');
insert into Categories (category_id, category_name) values (345, 'Technology');
insert into Categories (category_id, category_name) values (346, 'Energy');
insert into Categories (category_id, category_name) values (347, 'Finance');
insert into Categories (category_id, category_name) values (348, 'Capital Goods');
insert into Categories (category_id, category_name) values (349, 'Finance');
insert into Categories (category_id, category_name) values (350, 'Basic Industries');
insert into Categories (category_id, category_name) values (351, 'Health Care');
insert into Categories (category_id, category_name) values (352, 'Capital Goods');
insert into Categories (category_id, category_name) values (353, 'Energy');
insert into Categories (category_id, category_name) values (354, 'Consumer Services');
insert into Categories (category_id, category_name) values (355, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (356, 'Health Care');
insert into Categories (category_id, category_name) values (357, 'Capital Goods');
insert into Categories (category_id, category_name) values (358, 'Finance');
insert into Categories (category_id, category_name) values (359, 'n/a');
insert into Categories (category_id, category_name) values (360, 'Consumer Services');
insert into Categories (category_id, category_name) values (361, 'n/a');
insert into Categories (category_id, category_name) values (362, 'Health Care');
insert into Categories (category_id, category_name) values (363, 'n/a');
insert into Categories (category_id, category_name) values (364, 'Finance');
insert into Categories (category_id, category_name) values (365, 'Technology');
insert into Categories (category_id, category_name) values (366, 'Public Utilities');
insert into Categories (category_id, category_name) values (367, 'Finance');
insert into Categories (category_id, category_name) values (368, 'Consumer Services');
insert into Categories (category_id, category_name) values (369, 'n/a');
insert into Categories (category_id, category_name) values (370, 'n/a');
insert into Categories (category_id, category_name) values (371, 'Finance');
insert into Categories (category_id, category_name) values (372, 'Finance');
insert into Categories (category_id, category_name) values (373, 'Finance');
insert into Categories (category_id, category_name) values (374, 'Miscellaneous');
insert into Categories (category_id, category_name) values (375, 'Capital Goods');
insert into Categories (category_id, category_name) values (376, 'Public Utilities');
insert into Categories (category_id, category_name) values (377, 'Basic Industries');
insert into Categories (category_id, category_name) values (378, 'Health Care');
insert into Categories (category_id, category_name) values (379, 'Public Utilities');
insert into Categories (category_id, category_name) values (380, 'Finance');
insert into Categories (category_id, category_name) values (381, 'Energy');
insert into Categories (category_id, category_name) values (382, 'Consumer Services');
insert into Categories (category_id, category_name) values (383, 'n/a');
insert into Categories (category_id, category_name) values (384, 'Finance');
insert into Categories (category_id, category_name) values (385, 'Basic Industries');
insert into Categories (category_id, category_name) values (386, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (387, 'Finance');
insert into Categories (category_id, category_name) values (388, 'n/a');
insert into Categories (category_id, category_name) values (389, 'Consumer Services');
insert into Categories (category_id, category_name) values (390, 'Consumer Services');
insert into Categories (category_id, category_name) values (391, 'Finance');
insert into Categories (category_id, category_name) values (392, 'Energy');
insert into Categories (category_id, category_name) values (393, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (394, 'n/a');
insert into Categories (category_id, category_name) values (395, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (396, 'Health Care');
insert into Categories (category_id, category_name) values (397, 'Capital Goods');
insert into Categories (category_id, category_name) values (398, 'Energy');
insert into Categories (category_id, category_name) values (399, 'Technology');
insert into Categories (category_id, category_name) values (400, 'Consumer Services');
insert into Categories (category_id, category_name) values (401, 'Technology');
insert into Categories (category_id, category_name) values (402, 'Transportation');
insert into Categories (category_id, category_name) values (403, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (404, 'Miscellaneous');
insert into Categories (category_id, category_name) values (405, 'Health Care');
insert into Categories (category_id, category_name) values (406, 'Finance');
insert into Categories (category_id, category_name) values (407, 'Energy');
insert into Categories (category_id, category_name) values (408, 'Consumer Services');
insert into Categories (category_id, category_name) values (409, 'n/a');
insert into Categories (category_id, category_name) values (410, 'Finance');
insert into Categories (category_id, category_name) values (411, 'n/a');
insert into Categories (category_id, category_name) values (412, 'Capital Goods');
insert into Categories (category_id, category_name) values (413, 'Health Care');
insert into Categories (category_id, category_name) values (414, 'Health Care');
insert into Categories (category_id, category_name) values (415, 'Energy');
insert into Categories (category_id, category_name) values (416, 'Consumer Services');
insert into Categories (category_id, category_name) values (417, 'n/a');
insert into Categories (category_id, category_name) values (418, 'Basic Industries');
insert into Categories (category_id, category_name) values (419, 'n/a');
insert into Categories (category_id, category_name) values (420, 'n/a');
insert into Categories (category_id, category_name) values (421, 'Finance');
insert into Categories (category_id, category_name) values (422, 'Energy');
insert into Categories (category_id, category_name) values (423, 'Public Utilities');
insert into Categories (category_id, category_name) values (424, 'Finance');
insert into Categories (category_id, category_name) values (425, 'Finance');
insert into Categories (category_id, category_name) values (426, 'Miscellaneous');
insert into Categories (category_id, category_name) values (427, 'Public Utilities');
insert into Categories (category_id, category_name) values (428, 'Technology');
insert into Categories (category_id, category_name) values (429, 'Finance');
insert into Categories (category_id, category_name) values (430, 'Finance');
insert into Categories (category_id, category_name) values (431, 'Basic Industries');
insert into Categories (category_id, category_name) values (432, 'Finance');
insert into Categories (category_id, category_name) values (433, 'Public Utilities');
insert into Categories (category_id, category_name) values (434, 'Health Care');
insert into Categories (category_id, category_name) values (435, 'Energy');
insert into Categories (category_id, category_name) values (436, 'Technology');
insert into Categories (category_id, category_name) values (437, 'n/a');
insert into Categories (category_id, category_name) values (438, 'Technology');
insert into Categories (category_id, category_name) values (439, 'n/a');
insert into Categories (category_id, category_name) values (440, 'Health Care');
insert into Categories (category_id, category_name) values (441, 'Capital Goods');
insert into Categories (category_id, category_name) values (442, 'Consumer Services');
insert into Categories (category_id, category_name) values (443, 'Technology');
insert into Categories (category_id, category_name) values (444, 'n/a');
insert into Categories (category_id, category_name) values (445, 'Health Care');
insert into Categories (category_id, category_name) values (446, 'Consumer Services');
insert into Categories (category_id, category_name) values (447, 'Finance');
insert into Categories (category_id, category_name) values (448, 'Consumer Services');
insert into Categories (category_id, category_name) values (449, 'n/a');
insert into Categories (category_id, category_name) values (450, 'Consumer Durables');
insert into Categories (category_id, category_name) values (451, 'Health Care');
insert into Categories (category_id, category_name) values (452, 'Consumer Services');
insert into Categories (category_id, category_name) values (453, 'Basic Industries');
insert into Categories (category_id, category_name) values (454, 'Health Care');
insert into Categories (category_id, category_name) values (455, 'n/a');
insert into Categories (category_id, category_name) values (456, 'Capital Goods');
insert into Categories (category_id, category_name) values (457, 'Finance');
insert into Categories (category_id, category_name) values (458, 'Consumer Durables');
insert into Categories (category_id, category_name) values (459, 'Technology');
insert into Categories (category_id, category_name) values (460, 'n/a');
insert into Categories (category_id, category_name) values (461, 'Health Care');
insert into Categories (category_id, category_name) values (462, 'Capital Goods');
insert into Categories (category_id, category_name) values (463, 'n/a');
insert into Categories (category_id, category_name) values (464, 'n/a');
insert into Categories (category_id, category_name) values (465, 'Capital Goods');
insert into Categories (category_id, category_name) values (466, 'Basic Industries');
insert into Categories (category_id, category_name) values (467, 'Public Utilities');
insert into Categories (category_id, category_name) values (468, 'n/a');
insert into Categories (category_id, category_name) values (469, 'Technology');
insert into Categories (category_id, category_name) values (470, 'Finance');
insert into Categories (category_id, category_name) values (471, 'n/a');
insert into Categories (category_id, category_name) values (472, 'Public Utilities');
insert into Categories (category_id, category_name) values (473, 'Public Utilities');
insert into Categories (category_id, category_name) values (474, 'Health Care');
insert into Categories (category_id, category_name) values (475, 'Finance');
insert into Categories (category_id, category_name) values (476, 'Capital Goods');
insert into Categories (category_id, category_name) values (477, 'n/a');
insert into Categories (category_id, category_name) values (478, 'Health Care');
insert into Categories (category_id, category_name) values (479, 'n/a');
insert into Categories (category_id, category_name) values (480, 'Finance');
insert into Categories (category_id, category_name) values (481, 'Capital Goods');
insert into Categories (category_id, category_name) values (482, 'n/a');
insert into Categories (category_id, category_name) values (483, 'n/a');
insert into Categories (category_id, category_name) values (484, 'Capital Goods');
insert into Categories (category_id, category_name) values (485, 'Consumer Services');
insert into Categories (category_id, category_name) values (486, 'Health Care');
insert into Categories (category_id, category_name) values (487, 'Health Care');
insert into Categories (category_id, category_name) values (488, 'Public Utilities');
insert into Categories (category_id, category_name) values (489, 'Consumer Services');
insert into Categories (category_id, category_name) values (490, 'Public Utilities');
insert into Categories (category_id, category_name) values (491, 'Energy');
insert into Categories (category_id, category_name) values (492, 'Health Care');
insert into Categories (category_id, category_name) values (493, 'n/a');
insert into Categories (category_id, category_name) values (494, 'Public Utilities');
insert into Categories (category_id, category_name) values (495, 'n/a');
insert into Categories (category_id, category_name) values (496, 'Consumer Services');
insert into Categories (category_id, category_name) values (497, 'n/a');
insert into Categories (category_id, category_name) values (498, 'Public Utilities');
insert into Categories (category_id, category_name) values (499, 'Health Care');
insert into Categories (category_id, category_name) values (500, 'Health Care');
insert into Categories (category_id, category_name) values (501, 'Finance');
insert into Categories (category_id, category_name) values (502, 'Health Care');
insert into Categories (category_id, category_name) values (503, 'Consumer Services');
insert into Categories (category_id, category_name) values (504, 'Consumer Services');
insert into Categories (category_id, category_name) values (505, 'Consumer Services');
insert into Categories (category_id, category_name) values (506, 'Consumer Services');
insert into Categories (category_id, category_name) values (507, 'Finance');
insert into Categories (category_id, category_name) values (508, 'n/a');
insert into Categories (category_id, category_name) values (509, 'Technology');
insert into Categories (category_id, category_name) values (510, 'n/a');
insert into Categories (category_id, category_name) values (511, 'Finance');
insert into Categories (category_id, category_name) values (512, 'Technology');
insert into Categories (category_id, category_name) values (513, 'Energy');
insert into Categories (category_id, category_name) values (514, 'Energy');
insert into Categories (category_id, category_name) values (515, 'Technology');
insert into Categories (category_id, category_name) values (516, 'n/a');
insert into Categories (category_id, category_name) values (517, 'Capital Goods');
insert into Categories (category_id, category_name) values (518, 'Consumer Services');
insert into Categories (category_id, category_name) values (519, 'Technology');
insert into Categories (category_id, category_name) values (520, 'Finance');
insert into Categories (category_id, category_name) values (521, 'n/a');
insert into Categories (category_id, category_name) values (522, 'Finance');
insert into Categories (category_id, category_name) values (523, 'Technology');
insert into Categories (category_id, category_name) values (524, 'n/a');
insert into Categories (category_id, category_name) values (525, 'n/a');
insert into Categories (category_id, category_name) values (526, 'Energy');
insert into Categories (category_id, category_name) values (527, 'Finance');
insert into Categories (category_id, category_name) values (528, 'Energy');
insert into Categories (category_id, category_name) values (529, 'Health Care');
insert into Categories (category_id, category_name) values (530, 'Finance');
insert into Categories (category_id, category_name) values (531, 'Health Care');
insert into Categories (category_id, category_name) values (532, 'Consumer Services');
insert into Categories (category_id, category_name) values (533, 'Technology');
insert into Categories (category_id, category_name) values (534, 'Health Care');
insert into Categories (category_id, category_name) values (535, 'Technology');
insert into Categories (category_id, category_name) values (536, 'Basic Industries');
insert into Categories (category_id, category_name) values (537, 'Health Care');
insert into Categories (category_id, category_name) values (538, 'n/a');
insert into Categories (category_id, category_name) values (539, 'n/a');
insert into Categories (category_id, category_name) values (540, 'Transportation');
insert into Categories (category_id, category_name) values (541, 'n/a');
insert into Categories (category_id, category_name) values (542, 'n/a');
insert into Categories (category_id, category_name) values (543, 'Transportation');
insert into Categories (category_id, category_name) values (544, 'Health Care');
insert into Categories (category_id, category_name) values (545, 'Finance');
insert into Categories (category_id, category_name) values (546, 'Capital Goods');
insert into Categories (category_id, category_name) values (547, 'n/a');
insert into Categories (category_id, category_name) values (548, 'Public Utilities');
insert into Categories (category_id, category_name) values (549, 'n/a');
insert into Categories (category_id, category_name) values (550, 'Consumer Services');
insert into Categories (category_id, category_name) values (551, 'Technology');
insert into Categories (category_id, category_name) values (552, 'Public Utilities');
insert into Categories (category_id, category_name) values (553, 'Consumer Durables');
insert into Categories (category_id, category_name) values (554, 'Health Care');
insert into Categories (category_id, category_name) values (555, 'Finance');
insert into Categories (category_id, category_name) values (556, 'Miscellaneous');
insert into Categories (category_id, category_name) values (557, 'Finance');
insert into Categories (category_id, category_name) values (558, 'n/a');
insert into Categories (category_id, category_name) values (559, 'Technology');
insert into Categories (category_id, category_name) values (560, 'Finance');
insert into Categories (category_id, category_name) values (561, 'Health Care');
insert into Categories (category_id, category_name) values (562, 'Public Utilities');
insert into Categories (category_id, category_name) values (563, 'n/a');
insert into Categories (category_id, category_name) values (564, 'n/a');
insert into Categories (category_id, category_name) values (565, 'Public Utilities');
insert into Categories (category_id, category_name) values (566, 'Consumer Durables');
insert into Categories (category_id, category_name) values (567, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (568, 'Health Care');
insert into Categories (category_id, category_name) values (569, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (570, 'n/a');
insert into Categories (category_id, category_name) values (571, 'Health Care');
insert into Categories (category_id, category_name) values (572, 'Miscellaneous');
insert into Categories (category_id, category_name) values (573, 'Capital Goods');
insert into Categories (category_id, category_name) values (574, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (575, 'Finance');
insert into Categories (category_id, category_name) values (576, 'Technology');
insert into Categories (category_id, category_name) values (577, 'Finance');
insert into Categories (category_id, category_name) values (578, 'Basic Industries');
insert into Categories (category_id, category_name) values (579, 'Capital Goods');
insert into Categories (category_id, category_name) values (580, 'Transportation');
insert into Categories (category_id, category_name) values (581, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (582, 'n/a');
insert into Categories (category_id, category_name) values (583, 'Technology');
insert into Categories (category_id, category_name) values (584, 'Health Care');
insert into Categories (category_id, category_name) values (585, 'n/a');
insert into Categories (category_id, category_name) values (586, 'n/a');
insert into Categories (category_id, category_name) values (587, 'n/a');
insert into Categories (category_id, category_name) values (588, 'Finance');
insert into Categories (category_id, category_name) values (589, 'n/a');
insert into Categories (category_id, category_name) values (590, 'Consumer Services');
insert into Categories (category_id, category_name) values (591, 'Consumer Services');
insert into Categories (category_id, category_name) values (592, 'n/a');
insert into Categories (category_id, category_name) values (593, 'Health Care');
insert into Categories (category_id, category_name) values (594, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (595, 'Capital Goods');
insert into Categories (category_id, category_name) values (596, 'Public Utilities');
insert into Categories (category_id, category_name) values (597, 'Consumer Durables');
insert into Categories (category_id, category_name) values (598, 'Finance');
insert into Categories (category_id, category_name) values (599, 'Consumer Services');
insert into Categories (category_id, category_name) values (600, 'n/a');
insert into Categories (category_id, category_name) values (601, 'Public Utilities');
insert into Categories (category_id, category_name) values (602, 'Public Utilities');
insert into Categories (category_id, category_name) values (603, 'Finance');
insert into Categories (category_id, category_name) values (604, 'Miscellaneous');
insert into Categories (category_id, category_name) values (605, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (606, 'Health Care');
insert into Categories (category_id, category_name) values (607, 'Basic Industries');
insert into Categories (category_id, category_name) values (608, 'Health Care');
insert into Categories (category_id, category_name) values (609, 'n/a');
insert into Categories (category_id, category_name) values (610, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (611, 'Basic Industries');
insert into Categories (category_id, category_name) values (612, 'Technology');
insert into Categories (category_id, category_name) values (613, 'n/a');
insert into Categories (category_id, category_name) values (614, 'Energy');
insert into Categories (category_id, category_name) values (615, 'n/a');
insert into Categories (category_id, category_name) values (616, 'n/a');
insert into Categories (category_id, category_name) values (617, 'Capital Goods');
insert into Categories (category_id, category_name) values (618, 'Technology');
insert into Categories (category_id, category_name) values (619, 'Finance');
insert into Categories (category_id, category_name) values (620, 'Health Care');
insert into Categories (category_id, category_name) values (621, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (622, 'Finance');
insert into Categories (category_id, category_name) values (623, 'n/a');
insert into Categories (category_id, category_name) values (624, 'Health Care');
insert into Categories (category_id, category_name) values (625, 'Energy');
insert into Categories (category_id, category_name) values (626, 'n/a');
insert into Categories (category_id, category_name) values (627, 'Technology');
insert into Categories (category_id, category_name) values (628, 'Consumer Services');
insert into Categories (category_id, category_name) values (629, 'Technology');
insert into Categories (category_id, category_name) values (630, 'n/a');
insert into Categories (category_id, category_name) values (631, 'Technology');
insert into Categories (category_id, category_name) values (632, 'n/a');
insert into Categories (category_id, category_name) values (633, 'Consumer Services');
insert into Categories (category_id, category_name) values (634, 'n/a');
insert into Categories (category_id, category_name) values (635, 'Finance');
insert into Categories (category_id, category_name) values (636, 'Transportation');
insert into Categories (category_id, category_name) values (637, 'Finance');
insert into Categories (category_id, category_name) values (638, 'Basic Industries');
insert into Categories (category_id, category_name) values (639, 'Health Care');
insert into Categories (category_id, category_name) values (640, 'Energy');
insert into Categories (category_id, category_name) values (641, 'n/a');
insert into Categories (category_id, category_name) values (642, 'Capital Goods');
insert into Categories (category_id, category_name) values (643, 'Health Care');
insert into Categories (category_id, category_name) values (644, 'Miscellaneous');
insert into Categories (category_id, category_name) values (645, 'Health Care');
insert into Categories (category_id, category_name) values (646, 'Consumer Services');
insert into Categories (category_id, category_name) values (647, 'Energy');
insert into Categories (category_id, category_name) values (648, 'Health Care');
insert into Categories (category_id, category_name) values (649, 'Basic Industries');
insert into Categories (category_id, category_name) values (650, 'Consumer Services');
insert into Categories (category_id, category_name) values (651, 'Health Care');
insert into Categories (category_id, category_name) values (652, 'n/a');
insert into Categories (category_id, category_name) values (653, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (654, 'Basic Industries');
insert into Categories (category_id, category_name) values (655, 'Public Utilities');
insert into Categories (category_id, category_name) values (656, 'n/a');
insert into Categories (category_id, category_name) values (657, 'Technology');
insert into Categories (category_id, category_name) values (658, 'Finance');
insert into Categories (category_id, category_name) values (659, 'Technology');
insert into Categories (category_id, category_name) values (660, 'Finance');
insert into Categories (category_id, category_name) values (661, 'n/a');
insert into Categories (category_id, category_name) values (662, 'Consumer Durables');
insert into Categories (category_id, category_name) values (663, 'n/a');
insert into Categories (category_id, category_name) values (664, 'Consumer Services');
insert into Categories (category_id, category_name) values (665, 'Health Care');
insert into Categories (category_id, category_name) values (666, 'n/a');
insert into Categories (category_id, category_name) values (667, 'n/a');
insert into Categories (category_id, category_name) values (668, 'n/a');
insert into Categories (category_id, category_name) values (669, 'Technology');
insert into Categories (category_id, category_name) values (670, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (671, 'Health Care');
insert into Categories (category_id, category_name) values (672, 'Finance');
insert into Categories (category_id, category_name) values (673, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (674, 'Consumer Durables');
insert into Categories (category_id, category_name) values (675, 'n/a');
insert into Categories (category_id, category_name) values (676, 'Basic Industries');
insert into Categories (category_id, category_name) values (677, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (678, 'Consumer Services');
insert into Categories (category_id, category_name) values (679, 'n/a');
insert into Categories (category_id, category_name) values (680, 'n/a');
insert into Categories (category_id, category_name) values (681, 'Basic Industries');
insert into Categories (category_id, category_name) values (682, 'Consumer Services');
insert into Categories (category_id, category_name) values (683, 'Consumer Services');
insert into Categories (category_id, category_name) values (684, 'Consumer Services');
insert into Categories (category_id, category_name) values (685, 'n/a');
insert into Categories (category_id, category_name) values (686, 'Finance');
insert into Categories (category_id, category_name) values (687, 'Basic Industries');
insert into Categories (category_id, category_name) values (688, 'Consumer Services');
insert into Categories (category_id, category_name) values (689, 'Consumer Durables');
insert into Categories (category_id, category_name) values (690, 'Technology');
insert into Categories (category_id, category_name) values (691, 'Technology');
insert into Categories (category_id, category_name) values (692, 'n/a');
insert into Categories (category_id, category_name) values (693, 'Consumer Durables');
insert into Categories (category_id, category_name) values (694, 'Consumer Services');
insert into Categories (category_id, category_name) values (695, 'Technology');
insert into Categories (category_id, category_name) values (696, 'Transportation');
insert into Categories (category_id, category_name) values (697, 'Finance');
insert into Categories (category_id, category_name) values (698, 'n/a');
insert into Categories (category_id, category_name) values (699, 'n/a');
insert into Categories (category_id, category_name) values (700, 'Basic Industries');
insert into Categories (category_id, category_name) values (701, 'n/a');
insert into Categories (category_id, category_name) values (702, 'Health Care');
insert into Categories (category_id, category_name) values (703, 'Health Care');
insert into Categories (category_id, category_name) values (704, 'Technology');
insert into Categories (category_id, category_name) values (705, 'Health Care');
insert into Categories (category_id, category_name) values (706, 'Finance');
insert into Categories (category_id, category_name) values (707, 'Basic Industries');
insert into Categories (category_id, category_name) values (708, 'n/a');
insert into Categories (category_id, category_name) values (709, 'Health Care');
insert into Categories (category_id, category_name) values (710, 'Energy');
insert into Categories (category_id, category_name) values (711, 'Health Care');
insert into Categories (category_id, category_name) values (712, 'Finance');
insert into Categories (category_id, category_name) values (713, 'Finance');
insert into Categories (category_id, category_name) values (714, 'Technology');
insert into Categories (category_id, category_name) values (715, 'n/a');
insert into Categories (category_id, category_name) values (716, 'n/a');
insert into Categories (category_id, category_name) values (717, 'Finance');
insert into Categories (category_id, category_name) values (718, 'Finance');
insert into Categories (category_id, category_name) values (719, 'Health Care');
insert into Categories (category_id, category_name) values (720, 'n/a');
insert into Categories (category_id, category_name) values (721, 'Public Utilities');
insert into Categories (category_id, category_name) values (722, 'Capital Goods');
insert into Categories (category_id, category_name) values (723, 'Capital Goods');
insert into Categories (category_id, category_name) values (724, 'Miscellaneous');
insert into Categories (category_id, category_name) values (725, 'Finance');
insert into Categories (category_id, category_name) values (726, 'Consumer Services');
insert into Categories (category_id, category_name) values (727, 'n/a');
insert into Categories (category_id, category_name) values (728, 'n/a');
insert into Categories (category_id, category_name) values (729, 'Finance');
insert into Categories (category_id, category_name) values (730, 'Health Care');
insert into Categories (category_id, category_name) values (731, 'Capital Goods');
insert into Categories (category_id, category_name) values (732, 'Capital Goods');
insert into Categories (category_id, category_name) values (733, 'Consumer Services');
insert into Categories (category_id, category_name) values (734, 'n/a');
insert into Categories (category_id, category_name) values (735, 'Energy');
insert into Categories (category_id, category_name) values (736, 'n/a');
insert into Categories (category_id, category_name) values (737, 'n/a');
insert into Categories (category_id, category_name) values (738, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (739, 'Finance');
insert into Categories (category_id, category_name) values (740, 'Health Care');
insert into Categories (category_id, category_name) values (741, 'Consumer Services');
insert into Categories (category_id, category_name) values (742, 'n/a');
insert into Categories (category_id, category_name) values (743, 'Finance');
insert into Categories (category_id, category_name) values (744, 'Public Utilities');
insert into Categories (category_id, category_name) values (745, 'Finance');
insert into Categories (category_id, category_name) values (746, 'Basic Industries');
insert into Categories (category_id, category_name) values (747, 'Technology');
insert into Categories (category_id, category_name) values (748, 'Finance');
insert into Categories (category_id, category_name) values (749, 'Health Care');
insert into Categories (category_id, category_name) values (750, 'Technology');
insert into Categories (category_id, category_name) values (751, 'Finance');
insert into Categories (category_id, category_name) values (752, 'Capital Goods');
insert into Categories (category_id, category_name) values (753, 'Technology');
insert into Categories (category_id, category_name) values (754, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (755, 'Consumer Services');
insert into Categories (category_id, category_name) values (756, 'Basic Industries');
insert into Categories (category_id, category_name) values (757, 'Technology');
insert into Categories (category_id, category_name) values (758, 'Basic Industries');
insert into Categories (category_id, category_name) values (759, 'Consumer Services');
insert into Categories (category_id, category_name) values (760, 'Transportation');
insert into Categories (category_id, category_name) values (761, 'Technology');
insert into Categories (category_id, category_name) values (762, 'Technology');
insert into Categories (category_id, category_name) values (763, 'n/a');
insert into Categories (category_id, category_name) values (764, 'n/a');
insert into Categories (category_id, category_name) values (765, 'Consumer Services');
insert into Categories (category_id, category_name) values (766, 'Finance');
insert into Categories (category_id, category_name) values (767, 'n/a');
insert into Categories (category_id, category_name) values (768, 'n/a');
insert into Categories (category_id, category_name) values (769, 'Consumer Services');
insert into Categories (category_id, category_name) values (770, 'Health Care');
insert into Categories (category_id, category_name) values (771, 'Consumer Services');
insert into Categories (category_id, category_name) values (772, 'Consumer Durables');
insert into Categories (category_id, category_name) values (773, 'Transportation');
insert into Categories (category_id, category_name) values (774, 'Energy');
insert into Categories (category_id, category_name) values (775, 'Energy');
insert into Categories (category_id, category_name) values (776, 'Finance');
insert into Categories (category_id, category_name) values (777, 'n/a');
insert into Categories (category_id, category_name) values (778, 'Capital Goods');
insert into Categories (category_id, category_name) values (779, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (780, 'Health Care');
insert into Categories (category_id, category_name) values (781, 'n/a');
insert into Categories (category_id, category_name) values (782, 'Technology');
insert into Categories (category_id, category_name) values (783, 'Capital Goods');
insert into Categories (category_id, category_name) values (784, 'Public Utilities');
insert into Categories (category_id, category_name) values (785, 'Finance');
insert into Categories (category_id, category_name) values (786, 'Basic Industries');
insert into Categories (category_id, category_name) values (787, 'Consumer Services');
insert into Categories (category_id, category_name) values (788, 'Health Care');
insert into Categories (category_id, category_name) values (789, 'Health Care');
insert into Categories (category_id, category_name) values (790, 'Miscellaneous');
insert into Categories (category_id, category_name) values (791, 'n/a');
insert into Categories (category_id, category_name) values (792, 'Capital Goods');
insert into Categories (category_id, category_name) values (793, 'n/a');
insert into Categories (category_id, category_name) values (794, 'n/a');
insert into Categories (category_id, category_name) values (795, 'Finance');
insert into Categories (category_id, category_name) values (796, 'Technology');
insert into Categories (category_id, category_name) values (797, 'Finance');
insert into Categories (category_id, category_name) values (798, 'Consumer Services');
insert into Categories (category_id, category_name) values (799, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (800, 'Finance');
insert into Categories (category_id, category_name) values (801, 'Finance');
insert into Categories (category_id, category_name) values (802, 'Health Care');
insert into Categories (category_id, category_name) values (803, 'Energy');
insert into Categories (category_id, category_name) values (804, 'Public Utilities');
insert into Categories (category_id, category_name) values (805, 'Technology');
insert into Categories (category_id, category_name) values (806, 'n/a');
insert into Categories (category_id, category_name) values (807, 'Basic Industries');
insert into Categories (category_id, category_name) values (808, 'Basic Industries');
insert into Categories (category_id, category_name) values (809, 'Consumer Services');
insert into Categories (category_id, category_name) values (810, 'Capital Goods');
insert into Categories (category_id, category_name) values (811, 'Health Care');
insert into Categories (category_id, category_name) values (812, 'n/a');
insert into Categories (category_id, category_name) values (813, 'n/a');
insert into Categories (category_id, category_name) values (814, 'n/a');
insert into Categories (category_id, category_name) values (815, 'Health Care');
insert into Categories (category_id, category_name) values (816, 'Health Care');
insert into Categories (category_id, category_name) values (817, 'Finance');
insert into Categories (category_id, category_name) values (818, 'Energy');
insert into Categories (category_id, category_name) values (819, 'Finance');
insert into Categories (category_id, category_name) values (820, 'n/a');
insert into Categories (category_id, category_name) values (821, 'Finance');
insert into Categories (category_id, category_name) values (822, 'Consumer Services');
insert into Categories (category_id, category_name) values (823, 'Technology');
insert into Categories (category_id, category_name) values (824, 'Health Care');
insert into Categories (category_id, category_name) values (825, 'Finance');
insert into Categories (category_id, category_name) values (826, 'n/a');
insert into Categories (category_id, category_name) values (827, 'Technology');
insert into Categories (category_id, category_name) values (828, 'n/a');
insert into Categories (category_id, category_name) values (829, 'Energy');
insert into Categories (category_id, category_name) values (830, 'Miscellaneous');
insert into Categories (category_id, category_name) values (831, 'Health Care');
insert into Categories (category_id, category_name) values (832, 'Energy');
insert into Categories (category_id, category_name) values (833, 'n/a');
insert into Categories (category_id, category_name) values (834, 'Finance');
insert into Categories (category_id, category_name) values (835, 'Consumer Services');
insert into Categories (category_id, category_name) values (836, 'n/a');
insert into Categories (category_id, category_name) values (837, 'Health Care');
insert into Categories (category_id, category_name) values (838, 'Finance');
insert into Categories (category_id, category_name) values (839, 'Health Care');
insert into Categories (category_id, category_name) values (840, 'Health Care');
insert into Categories (category_id, category_name) values (841, 'Energy');
insert into Categories (category_id, category_name) values (842, 'n/a');
insert into Categories (category_id, category_name) values (843, 'Finance');
insert into Categories (category_id, category_name) values (844, 'Finance');
insert into Categories (category_id, category_name) values (845, 'Consumer Services');
insert into Categories (category_id, category_name) values (846, 'n/a');
insert into Categories (category_id, category_name) values (847, 'Finance');
insert into Categories (category_id, category_name) values (848, 'Basic Industries');
insert into Categories (category_id, category_name) values (849, 'Public Utilities');
insert into Categories (category_id, category_name) values (850, 'Public Utilities');
insert into Categories (category_id, category_name) values (851, 'Finance');
insert into Categories (category_id, category_name) values (852, 'Technology');
insert into Categories (category_id, category_name) values (853, 'Consumer Durables');
insert into Categories (category_id, category_name) values (854, 'Consumer Services');
insert into Categories (category_id, category_name) values (855, 'Basic Industries');
insert into Categories (category_id, category_name) values (856, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (857, 'Basic Industries');
insert into Categories (category_id, category_name) values (858, 'Basic Industries');
insert into Categories (category_id, category_name) values (859, 'Miscellaneous');
insert into Categories (category_id, category_name) values (860, 'Finance');
insert into Categories (category_id, category_name) values (861, 'Health Care');
insert into Categories (category_id, category_name) values (862, 'n/a');
insert into Categories (category_id, category_name) values (863, 'n/a');
insert into Categories (category_id, category_name) values (864, 'n/a');
insert into Categories (category_id, category_name) values (865, 'Finance');
insert into Categories (category_id, category_name) values (866, 'n/a');
insert into Categories (category_id, category_name) values (867, 'Consumer Services');
insert into Categories (category_id, category_name) values (868, 'Technology');
insert into Categories (category_id, category_name) values (869, 'Health Care');
insert into Categories (category_id, category_name) values (870, 'Consumer Durables');
insert into Categories (category_id, category_name) values (871, 'Technology');
insert into Categories (category_id, category_name) values (872, 'Public Utilities');
insert into Categories (category_id, category_name) values (873, 'Miscellaneous');
insert into Categories (category_id, category_name) values (874, 'Technology');
insert into Categories (category_id, category_name) values (875, 'Finance');
insert into Categories (category_id, category_name) values (876, 'Finance');
insert into Categories (category_id, category_name) values (877, 'n/a');
insert into Categories (category_id, category_name) values (878, 'Finance');
insert into Categories (category_id, category_name) values (879, 'Finance');
insert into Categories (category_id, category_name) values (880, 'Consumer Durables');
insert into Categories (category_id, category_name) values (881, 'Consumer Durables');
insert into Categories (category_id, category_name) values (882, 'Health Care');
insert into Categories (category_id, category_name) values (883, 'Technology');
insert into Categories (category_id, category_name) values (884, 'Capital Goods');
insert into Categories (category_id, category_name) values (885, 'Health Care');
insert into Categories (category_id, category_name) values (886, 'Finance');
insert into Categories (category_id, category_name) values (887, 'Energy');
insert into Categories (category_id, category_name) values (888, 'Consumer Durables');
insert into Categories (category_id, category_name) values (889, 'n/a');
insert into Categories (category_id, category_name) values (890, 'Health Care');
insert into Categories (category_id, category_name) values (891, 'Health Care');
insert into Categories (category_id, category_name) values (892, 'Consumer Durables');
insert into Categories (category_id, category_name) values (893, 'n/a');
insert into Categories (category_id, category_name) values (894, 'n/a');
insert into Categories (category_id, category_name) values (895, 'Basic Industries');
insert into Categories (category_id, category_name) values (896, 'Finance');
insert into Categories (category_id, category_name) values (897, 'n/a');
insert into Categories (category_id, category_name) values (898, 'Technology');
insert into Categories (category_id, category_name) values (899, 'Capital Goods');
insert into Categories (category_id, category_name) values (900, 'Consumer Services');
insert into Categories (category_id, category_name) values (901, 'Public Utilities');
insert into Categories (category_id, category_name) values (902, 'Finance');
insert into Categories (category_id, category_name) values (903, 'Energy');
insert into Categories (category_id, category_name) values (904, 'Finance');
insert into Categories (category_id, category_name) values (905, 'Finance');
insert into Categories (category_id, category_name) values (906, 'Energy');
insert into Categories (category_id, category_name) values (907, 'Capital Goods');
insert into Categories (category_id, category_name) values (908, 'Consumer Services');
insert into Categories (category_id, category_name) values (909, 'Miscellaneous');
insert into Categories (category_id, category_name) values (910, 'n/a');
insert into Categories (category_id, category_name) values (911, 'Consumer Services');
insert into Categories (category_id, category_name) values (912, 'n/a');
insert into Categories (category_id, category_name) values (913, 'Health Care');
insert into Categories (category_id, category_name) values (914, 'Technology');
insert into Categories (category_id, category_name) values (915, 'n/a');
insert into Categories (category_id, category_name) values (916, 'Consumer Services');
insert into Categories (category_id, category_name) values (917, 'Finance');
insert into Categories (category_id, category_name) values (918, 'Consumer Services');
insert into Categories (category_id, category_name) values (919, 'Finance');
insert into Categories (category_id, category_name) values (920, 'Finance');
insert into Categories (category_id, category_name) values (921, 'Technology');
insert into Categories (category_id, category_name) values (922, 'Capital Goods');
insert into Categories (category_id, category_name) values (923, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (924, 'n/a');
insert into Categories (category_id, category_name) values (925, 'Technology');
insert into Categories (category_id, category_name) values (926, 'Health Care');
insert into Categories (category_id, category_name) values (927, 'Consumer Services');
insert into Categories (category_id, category_name) values (928, 'Consumer Services');
insert into Categories (category_id, category_name) values (929, 'n/a');
insert into Categories (category_id, category_name) values (930, 'Transportation');
insert into Categories (category_id, category_name) values (931, 'n/a');
insert into Categories (category_id, category_name) values (932, 'Capital Goods');
insert into Categories (category_id, category_name) values (933, 'Energy');
insert into Categories (category_id, category_name) values (934, 'n/a');
insert into Categories (category_id, category_name) values (935, 'Health Care');
insert into Categories (category_id, category_name) values (936, 'Public Utilities');
insert into Categories (category_id, category_name) values (937, 'Consumer Services');
insert into Categories (category_id, category_name) values (938, 'Health Care');
insert into Categories (category_id, category_name) values (939, 'Finance');
insert into Categories (category_id, category_name) values (940, 'Capital Goods');
insert into Categories (category_id, category_name) values (941, 'n/a');
insert into Categories (category_id, category_name) values (942, 'Finance');
insert into Categories (category_id, category_name) values (943, 'Public Utilities');
insert into Categories (category_id, category_name) values (944, 'Transportation');
insert into Categories (category_id, category_name) values (945, 'Finance');
insert into Categories (category_id, category_name) values (946, 'Health Care');
insert into Categories (category_id, category_name) values (947, 'Health Care');
insert into Categories (category_id, category_name) values (948, 'Health Care');
insert into Categories (category_id, category_name) values (949, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (950, 'Health Care');
insert into Categories (category_id, category_name) values (951, 'n/a');
insert into Categories (category_id, category_name) values (952, 'Public Utilities');
insert into Categories (category_id, category_name) values (953, 'n/a');
insert into Categories (category_id, category_name) values (954, 'Consumer Services');
insert into Categories (category_id, category_name) values (955, 'Capital Goods');
insert into Categories (category_id, category_name) values (956, 'Finance');
insert into Categories (category_id, category_name) values (957, 'n/a');
insert into Categories (category_id, category_name) values (958, 'Health Care');
insert into Categories (category_id, category_name) values (959, 'n/a');
insert into Categories (category_id, category_name) values (960, 'Energy');
insert into Categories (category_id, category_name) values (961, 'n/a');
insert into Categories (category_id, category_name) values (962, 'n/a');
insert into Categories (category_id, category_name) values (963, 'Energy');
insert into Categories (category_id, category_name) values (964, 'n/a');
insert into Categories (category_id, category_name) values (965, 'Capital Goods');
insert into Categories (category_id, category_name) values (966, 'Technology');
insert into Categories (category_id, category_name) values (967, 'Consumer Services');
insert into Categories (category_id, category_name) values (968, 'Finance');
insert into Categories (category_id, category_name) values (969, 'Public Utilities');
insert into Categories (category_id, category_name) values (970, 'n/a');
insert into Categories (category_id, category_name) values (971, 'Consumer Services');
insert into Categories (category_id, category_name) values (972, 'Technology');
insert into Categories (category_id, category_name) values (973, 'Finance');
insert into Categories (category_id, category_name) values (974, 'n/a');
insert into Categories (category_id, category_name) values (975, 'Finance');
insert into Categories (category_id, category_name) values (976, 'Finance');
insert into Categories (category_id, category_name) values (977, 'Technology');
insert into Categories (category_id, category_name) values (978, 'Health Care');
insert into Categories (category_id, category_name) values (979, 'Energy');
insert into Categories (category_id, category_name) values (980, 'Miscellaneous');
insert into Categories (category_id, category_name) values (981, 'Health Care');
insert into Categories (category_id, category_name) values (982, 'Basic Industries');
insert into Categories (category_id, category_name) values (983, 'Energy');
insert into Categories (category_id, category_name) values (984, 'n/a');
insert into Categories (category_id, category_name) values (985, 'n/a');
insert into Categories (category_id, category_name) values (986, 'Capital Goods');
insert into Categories (category_id, category_name) values (987, 'n/a');
insert into Categories (category_id, category_name) values (988, 'Consumer Services');
insert into Categories (category_id, category_name) values (989, 'Finance');
insert into Categories (category_id, category_name) values (990, 'n/a');
insert into Categories (category_id, category_name) values (991, 'n/a');
insert into Categories (category_id, category_name) values (992, 'Public Utilities');
insert into Categories (category_id, category_name) values (993, 'n/a');
insert into Categories (category_id, category_name) values (994, 'Finance');
insert into Categories (category_id, category_name) values (995, 'n/a');
insert into Categories (category_id, category_name) values (996, 'Consumer Services');
insert into Categories (category_id, category_name) values (997, 'Technology');
insert into Categories (category_id, category_name) values (998, 'Basic Industries');
insert into Categories (category_id, category_name) values (999, 'Consumer Non-Durables');
insert into Categories (category_id, category_name) values (1000, 'Health Care');
